spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: org.ably.circular
  paths-to-match: /**
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

security:
  jwt:
    expiration-time: ${JWT_EXPIRATION}
    secret-key: ${JWT_SECRET}
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

application:
  bucket:
    name: ${AWS_BUCKET_NAME}

logging:
  level:
    org:
      springframework:
        security: DEBUG