version: '3.8'

services:
  db:
    build: .
    container_name: dev-sync-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: circular_db
    ports:
      - "5432:5432"